### ISSUE TITLE
Toroidal codebox geometry not implemented correctly

### ISSUE THREAD

**Issue by jack-jjm** [Suppen/fish-interpreter#5]
The Fish instruction pointer is meant to wrap around when it reaches "the end of the code". This interpreter and the "official" (Python) one interpret "end of the code" in two different ways, which can be seen by running the program `'Ao'f0p`. With this interpreter, nothing it outputted, with the official one, it outputs an infinite string of A-s.

The problem seems to be that the official interpreter interprets "end of code" to mean "the character after the last non-zero character on a line or column", whereas this interpreter interprets it to mean "the first zero character on a line or column".

**Comment by Suppen** [comment]
The width and height of the codebox is set when the code is submitted, and never changed after that. The pointer will wrap whenever it reaches these dimensions, no matter what has been `p`ut outside it after the program started.

I'm working on fixing this, so it will automatically expand the codebox whenever something is `p`ut outside its bounds

**Comment by Suppen** [comment]
Fixed as of commit d3bed7ae32d0a841e1fd13c7d6db0779ec2663ee
