### ISSUE TITLE
Program fails if a line after the first is longer than it

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [Suppen/fish-interpreter#6]
Caused by [this line](https://github.com/Suppen/fish-interpreter/blob/master/lib/FishProgram.js#L124), when called by [`_normalizeGrid`](https://github.com/Suppen/fish-interpreter/blob/master/lib/FishProgram.js#L146). You can fix this probably by taking the max length of each line instead of the first line, or using some other method of obtaining the initial width for `_normalizeGrid`.

**Comment by ConorOBrien-Foxx** [comment]
it still isn't working on fishlanguage.com btw, you might have to update the dependencies

**Comment by Suppen** [comment]
Are you sure about that? It appears to work for me. Do you have an example of code which does not work? Can you try to force a complete reload with ctrl + f5?

**Comment by ConorOBrien-Foxx** [comment]
Hm, it wasn't working 6 hours ago. Blame caching I suppose, thanks!
