### ISSUE TITLE
Codebox shouldn't be a string

### ISSUE THREAD

**Issue by PidgeyUsedGust** [Suppen/fish-interpreter#7]
In the original Python implementation, any value could be put in the codebox using the `p` operator. Currently, if a number becomes too large or has an invalid character encoding, the interpreter will return 0.

For example,

    "Ā":*3ep3egn;

should output 65536, but here it will output 0.

**Comment by Suppen** [comment]
Fixed in commit 784bc7278581f93fd7560888b395479a9bad481d
